package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.ConsumerInfo;
@Mapper
public interface ConsumerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    int insert(ConsumerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    int insertSelective(ConsumerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    ConsumerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConsumerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumerInfo record);
}