package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.MessageRecord;
@Mapper
public interface MessageRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    int insert(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    int insertSelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    MessageRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageRecord record);
    
    /**
     * @Title: queryCallRecordByYearAndMonth
     * @Description: 自定义查询短信详单
     * @param year 查询年份
     * @param month 查询月份
     * @param phone 被查询的电话号码
     * @return CallRecord实体的list集合
     */
    List<MessageRecord> queryMassageByYearAndMonth(String year,String month,String phone);
    
}