package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.PhonePackage;
@Mapper
public interface PhonePackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    int insert(PhonePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    int insertSelective(PhonePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    PhonePackage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PhonePackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_package
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PhonePackage record);
}