package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.PointWeight;
@Mapper
public interface PointWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    int insert(PointWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    int insertSelective(PointWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    PointWeight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PointWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_weight
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PointWeight record);
}