package com.cms.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table call_record
 */
public class CallRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.call_from
     *
     * @mbg.generated
     */
    private String callFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.call_to
     *
     * @mbg.generated
     */
    private String callTo;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.call_time
     *
     * @mbg.generated
     */
    private Integer callTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.call_date
     *
     * @mbg.generated
     */
    private Date callDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record.call_money
     *
     * @mbg.generated
     */
    private BigDecimal callMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.id
     *
     * @return the value of call_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.id
     *
     * @param id the value for call_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_from
     *
     * @return the value of call_record.call_from
     *
     * @mbg.generated
     */
    public String getCallFrom() {
        return callFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_from
     *
     * @param callFrom the value for call_record.call_from
     *
     * @mbg.generated
     */
    public void setCallFrom(String callFrom) {
        this.callFrom = callFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_to
     *
     * @return the value of call_record.call_to
     *
     * @mbg.generated
     */
    public String getCallTo() {
        return callTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_to
     *
     * @param callTo the value for call_record.call_to
     *
     * @mbg.generated
     */
    public void setCallTo(String callTo) {
        this.callTo = callTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_time
     *
     * @return the value of call_record.call_time
     *
     * @mbg.generated
     */
    public Integer getCallTime() {
        return callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_time
     *
     * @param callTime the value for call_record.call_time
     *
     * @mbg.generated
     */
    public void setCallTime(Integer callTime) {
        this.callTime = callTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_date
     *
     * @return the value of call_record.call_date
     *
     * @mbg.generated
     */
    public Date getCallDate() {
        return callDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_date
     *
     * @param callDate the value for call_record.call_date
     *
     * @mbg.generated
     */
    public void setCallDate(Date callDate) {
        this.callDate = callDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record.call_money
     *
     * @return the value of call_record.call_money
     *
     * @mbg.generated
     */
    public BigDecimal getCallMoney() {
        return callMoney;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record.call_money
     *
     * @param callMoney the value for call_record.call_money
     *
     * @mbg.generated
     */
    public void setCallMoney(BigDecimal callMoney) {
        this.callMoney = callMoney;
    }
}