package com.cms.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table message_record
 */
public class MessageRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_type
     *
     * @mbg.generated
     */
    private Integer messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_from
     *
     * @mbg.generated
     */
    private String messageFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_from_to
     *
     * @mbg.generated
     */
    private String messageFromTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_date
     *
     * @mbg.generated
     */
    private Date messageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_money
     *
     * @mbg.generated
     */
    private BigDecimal messageMoney;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_record.message_status
     *
     * @mbg.generated
     */
    private Integer messageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.id
     *
     * @return the value of message_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.id
     *
     * @param id the value for message_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_type
     *
     * @return the value of message_record.message_type
     *
     * @mbg.generated
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_type
     *
     * @param messageType the value for message_record.message_type
     *
     * @mbg.generated
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_from
     *
     * @return the value of message_record.message_from
     *
     * @mbg.generated
     */
    public String getMessageFrom() {
        return messageFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_from
     *
     * @param messageFrom the value for message_record.message_from
     *
     * @mbg.generated
     */
    public void setMessageFrom(String messageFrom) {
        this.messageFrom = messageFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_from_to
     *
     * @return the value of message_record.message_from_to
     *
     * @mbg.generated
     */
    public String getMessageFromTo() {
        return messageFromTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_from_to
     *
     * @param messageFromTo the value for message_record.message_from_to
     *
     * @mbg.generated
     */
    public void setMessageFromTo(String messageFromTo) {
        this.messageFromTo = messageFromTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_date
     *
     * @return the value of message_record.message_date
     *
     * @mbg.generated
     */
    public Date getMessageDate() {
        return messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_date
     *
     * @param messageDate the value for message_record.message_date
     *
     * @mbg.generated
     */
    public void setMessageDate(Date messageDate) {
        this.messageDate = messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_money
     *
     * @return the value of message_record.message_money
     *
     * @mbg.generated
     */
    public BigDecimal getMessageMoney() {
        return messageMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_money
     *
     * @param messageMoney the value for message_record.message_money
     *
     * @mbg.generated
     */
    public void setMessageMoney(BigDecimal messageMoney) {
        this.messageMoney = messageMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_record.message_status
     *
     * @return the value of message_record.message_status
     *
     * @mbg.generated
     */
    public Integer getMessageStatus() {
        return messageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_record.message_status
     *
     * @param messageStatus the value for message_record.message_status
     *
     * @mbg.generated
     */
    public void setMessageStatus(Integer messageStatus) {
        this.messageStatus = messageStatus;
    }
}