package com.cms.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table point_num
 */
public class PointNum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_num.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_num.r_id
     *
     * @mbg.generated
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_num.point_num
     *
     * @mbg.generated
     */
    private Integer pointNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_num.point_useful_date
     *
     * @mbg.generated
     */
    private Date pointUsefulDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table point_num
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_num.id
     *
     * @return the value of point_num.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_num.id
     *
     * @param id the value for point_num.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_num.r_id
     *
     * @return the value of point_num.r_id
     *
     * @mbg.generated
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_num.r_id
     *
     * @param rId the value for point_num.r_id
     *
     * @mbg.generated
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_num.point_num
     *
     * @return the value of point_num.point_num
     *
     * @mbg.generated
     */
    public Integer getPointNum() {
        return pointNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_num.point_num
     *
     * @param pointNum the value for point_num.point_num
     *
     * @mbg.generated
     */
    public void setPointNum(Integer pointNum) {
        this.pointNum = pointNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_num.point_useful_date
     *
     * @return the value of point_num.point_useful_date
     *
     * @mbg.generated
     */
    public Date getPointUsefulDate() {
        return pointUsefulDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_num.point_useful_date
     *
     * @param pointUsefulDate the value for point_num.point_useful_date
     *
     * @mbg.generated
     */
    public void setPointUsefulDate(Date pointUsefulDate) {
        this.pointUsefulDate = pointUsefulDate;
    }
}