package com.cms.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table recharge_card
 */
public class RechargeCard implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_card.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *               
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_card.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_card.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_card.recharge_card_id
     *
     * @mbg.generated
     */
    private Long rechargeCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_card
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_card.id
     *
     * @return the value of recharge_card.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_card.id
     *
     * @param id the value for recharge_card.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_card.status
     *
     * @return the value of recharge_card.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_card.status
     *
     * @param status the value for recharge_card.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_card.amount
     *
     * @return the value of recharge_card.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_card.amount
     *
     * @param amount the value for recharge_card.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_card.recharge_card_id
     *
     * @return the value of recharge_card.recharge_card_id
     *
     * @mbg.generated
     */
    public Long getRechargeCardId() {
        return rechargeCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_card.recharge_card_id
     *
     * @param rechargeCardId the value for recharge_card.recharge_card_id
     *
     * @mbg.generated
     */
    public void setRechargeCardId(Long rechargeCardId) {
        this.rechargeCardId = rechargeCardId;
    }
}