package com.cms.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table recharge_history
 */
public class RechargeHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_history.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_history.consumer
     *
     * @mbg.generated
     */
    private Integer consumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_history.recharge_card_id
     *
     * @mbg.generated
     */
    private Integer rechargeCardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_history.id
     *
     * @return the value of recharge_history.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_history.id
     *
     * @param id the value for recharge_history.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_history.consumer
     *
     * @return the value of recharge_history.consumer
     *
     * @mbg.generated
     */
    public Integer getConsumer() {
        return consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_history.consumer
     *
     * @param consumer the value for recharge_history.consumer
     *
     * @mbg.generated
     */
    public void setConsumer(Integer consumer) {
        this.consumer = consumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_history.recharge_card_id
     *
     * @return the value of recharge_history.recharge_card_id
     *
     * @mbg.generated
     */
    public Integer getRechargeCardId() {
        return rechargeCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_history.recharge_card_id
     *
     * @param rechargeCardId the value for recharge_history.recharge_card_id
     *
     * @mbg.generated
     */
    public void setRechargeCardId(Integer rechargeCardId) {
        this.rechargeCardId = rechargeCardId;
    }
}