package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.CallRecord;
@Mapper
public interface CallRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    int insert(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    int insertSelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    CallRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CallRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CallRecord record);
    
    /**
     * @Title: queryCallRecordByYearAndMonth
     * @Description: 自定义查询通话详单
     * @param year 查询年份
     * @param month 查询月份
     * @param phone 被查询的电话号码
     * @return CallRecord实体的list集合
     */
    List<CallRecord> queryCallRecordByYearAndMonth(String year,String month,String phone);
}