package com.cms.mapper;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.ConsumerBasicInfo;
@Mapper
public interface ConsumerBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    int insert(ConsumerBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    int insertSelective(ConsumerBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    ConsumerBasicInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConsumerBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_basic_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumerBasicInfo record);
    /**
     * 
     * @Title: selectByPhoneNum
     * @Description: 使用手机号进行查询
     * @param phoneNum 手机号
     * @return 返回用户认证类
     */
    ConsumerBasicInfo selectByPhoneNum(String phoneNum);
    /**
     * 
     * @Title: selectIdByPhone
     * @Description: 使用手机号查询id
     * @param phone
     * @return
     */
    Integer selectIdByPhone(String phone);
}