package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.ConsumerHistory;
@Mapper
public interface ConsumerHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    int insert(ConsumerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    int insertSelective(ConsumerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    ConsumerHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConsumerHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumerHistory record);
    
    /**
     * 
     * @Title: selectByDateAndRid
     * @Description: 使用r_id和当前月份查询
     * @param id
     * @return
     */
    List<ConsumerHistory> selectByDateAndRid(Integer id);
    
    
}