package com.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.cms.pojo.RechargeHistory;
@Mapper
public interface RechargeHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    int insert(RechargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    int insertSelective(RechargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    RechargeHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RechargeHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RechargeHistory record);
    /**
     * 
     * @Title: selectByConsumer
     * @Description: 通过消费者信息查询缴费记录
     * @param consumer
     * @return
     */
    List<RechargeHistory> selectByConsumer(Integer consumer);
}